# Generated by Django 4.1.2 on 2022-10-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_alter_women_id_alter_women_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='category_id',
            new_name='category',
        ),
    ]
